### ISSUE TITLE
Plotting an ellipse

### ISSUE THREAD

**Issue by clndwhr** [jdfergason/Leaflet.Ellipse#2]
having issues trying to get any ellipse to populate. working with .8-dev version of leaflet, keeps kicking back a TypeError: this.callInitHooks is not a function. Line 251 of leaflet-src.js

Using the example provided with l.ellipse will populate this error however I can populate individual markers on a map

**Comment by jdfergason** [comment]
There were major API changes in 0.8 as it was a preview for 1.0.  The code is updated to work with leaflet 1.0.
